export const DEFAULT_NOTE_COLOR = '#FFFF5A';
export const DEFAULT_NOTE_COLOR_DARKER = '#FDDA0D';

export const AVAILABLE_COLORS = [
  DEFAULT_NOTE_COLOR,
  '#A7C7E7',
  '#85C385',
  '#DF9797',
  '#FFB347',
  '#F9F9F9',
];

export const AVAILABLE_COLORS_DARKER_SHADES = [
  DEFAULT_NOTE_COLOR_DARKER,
  '#8EAECE',
  '#63B263',
  '#D37070',
  '#E69A2E',
  '#ECECEC',
];

export const DEFAULT_MINIMUM_ROTATION_ANGLE = -10;
export const DEFAULT_MAXIMUM_ROTATION_ANGLE = 10;
