export const {
  REACT_APP_GRAASP_DEVELOPER_ID,
  REACT_APP_GRAASP_APP_ID,
  REACT_APP_VERSION,
  REACT_APP_GOOGLE_ANALYTICS_ID,
  REACT_APP_MOCK_API,
  REACT_APP_REFETCH_INTERVAL_SETTING,
} = process.env;
