export const dataCyWrapper = (selector: string): string =>
  `[data-cy="${selector}"]`;
export const SETTINGS_BUTTON_CY = 'settingsButton';
export const SETTINGS_CY = 'settings';
export const SCROLL_CONTAINER_CY = 'scrollContainer';
export const BACKGROUND_IMAGE_CY = 'backgroundImage';
export const SETTINGS_CLOSE_BTN_CY = 'settingsCloseButton';
export const NOTE_CONTAINER_CY = 'noteContainer';
export const NOTE_EDIT_DIALOG = 'noteEditDialog';
export const NOTE_CY = 'note';
export const RELOAD_BUTTON_CY = 'reloadButton';
export const DELETE_BUTTON_IN_DIALOG_CY = 'deleteButtonInDialog';
export const QUILL_DIALOG_CY = 'quillDialog';
export const NOTE_CONTENT_CY = 'noteContent';
export const CONFIRM_DELETE_DIALOG_CY = 'confirmDeleteDialog';
export const CANCEL_DELETE_BUTTON_CY = 'cancelDeleteButton';
export const CONFIRM_DELETE_BUTTON_CY = 'confirmDeleteButton';
export const CANCEL_DIALOG_CY = 'cancelDialog';
export const SAVE_DIALOG_CY = 'saveDialog';
